apiVersion: v1
kind: Service
metadata:
  name: cloudcart-product-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: product-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcart-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 531080694855.dkr.ecr.eu-north-1.amazonaws.com/cloudcart-product-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cloudcart-db:5432/cloudcart"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcart-order-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcart-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 531080694855.dkr.ecr.eu-north-1.amazonaws.com/cloudcart-order-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cloudcart-db:5432/cloudcart"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "250m"
